Changes for post install configuration
solusio/solus-go-sdk pull request #13
Opened 2020-09-27 12:22 UTC by oneumyvakin

TASK SIO-2396 Add License service
TASK SIO-2396 Add IP Blocks list
TASK SIO-2396 Add Compute Resource install step status error
TASK SIO-2396 Make IP Blocks and Location optionally at adding Compute Resource
TASK SIO-2396 Add WithLogger client option
TASK SIO-2396 Add Update method for User
TASK SIO-2396 Fix IsSnapshotsEnabled and add ImageFormat to Plan
TASK SIO-2396 Add Roles

2020-09-27 15:33 UTC, dshemin requested changes

2020-09-27 15:33 UTC, dshemin commented on computeResourcesInstallSteps.go
> +const (
Could you add `ComputeResourceInstallStepStatus` type, please.

2020-09-29 04:57 UTC, dshemin requested changes

2020-09-29 04:57 UTC, dshemin commented on computeResourcesInstallSteps.go
> +type ComputeResourceInstallStepStatus string
Please place `type` before constants. It's a common way to define enums in Golang.

2020-09-29 07:58 UTC, dshemin approved these changes
LGTM!

2020-09-29 08:25 UTC, oneumyvakin commented
Thank you!

2020-09-29 08:26 UTC, merged