Add Activity Logs service
solusio/solus-go-sdk pull request #79
Opened 2021-12-20 16:26 UTC by oneumyvakin

2021-12-20 16:35 UTC, dshemin commented
Please run `go generate` for generating pagination logic

2021-12-20 16:35 UTC, dshemin requested changes

2021-12-20 16:35 UTC, dshemin commented on activityLogs.go
> +type ActivityLogsEvent string
Please put this type definition above constants. It's a common way to define enums.

2021-12-22 03:41 UTC, dshemin approved these changes

2021-12-22 03:44 UTC, cyxrop approved these changes

2021-12-22 06:20 UTC, merged